### ISSUE TITLE
Keypresses in Jupyter notebook cells are captured by the camera controller

### ISSUE THREAD

**Issue by martinal** [martinal/unray#17]
When editing code in a notebook cell, arrow keypresses will move both the text cursor and the cameras in all the unray widgets. @vidartf do you know what this can be?

**Comment by vidartf** [comment]
The OrbitControls (and possible others) register their key events on the document. You can solve this by vendoring the controls and change it to only listen for key events on the canvas.

**Comment by martinal** [comment]
Now using pythreejs, the buggy code is deleted.
