### ISSUE TITLE
Xray renderer artifacts when position is not 0,0,0

### ISSUE THREAD

**Issue by vidartf** [martinal/unray#25]

**Comment by vidartf** [comment]
![unray](https://user-images.githubusercontent.com/510760/29783765-940f6204-8bef-11e7-8fc9-47dfecb1516d.png)

**Comment by martinal** [comment]
Thanks for finding. Do you mean `THREE.Mesh.position` or something else? Can you post code to reproduce?

**Comment by vidartf** [comment]
I think this might be when it is a child object. Is the shader maybe using the object matrix when it should be using the world matrix? Or is it there an 'updateNeeded' flag I'm not hitting maybe?

**Comment by martinal** [comment]
The shader is using camera coordinates in world space in calculations with object coordinates in object space. I have a local branch trying to fix it but I can't use blackbox to test.

**Comment by vidartf** [comment]
I'm working through pushing my local changes, I'll ping this issue again
once I have a reproducible environment that is published.

**Comment by martinal** [comment]
I pushed some fixes to the redesign branch, rebased on top of your things. Haven't tested it with xray+position yet.
